### ISSUE TITLE
The `1.21.1-alpine` tag on Docker Hub is missing multple OS/ARCH entries

### ISSUE THREAD

**Issue by JonasAlfredsson** [nginxinc/docker-nginx#561]
Hi, 

I am building an image for multiple architectures from this image and ran into the following error for the `linux/386` platform when building from the `1.21.1-alpine` tag:

```
error: failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: no match for platform in manifest
```

Looking at it on [Docker Hub](https://hub.docker.com/layers/nginx/library/nginx/1.21.1-alpine/images/sha256-833dc94560d9cdb945a0b83bb02b93372ce2dcdf34f4df30fe8f5656ce5d3fb5?context=explore) we indeed see that it is only available for the following architectures:

- linux/arm64/v8
- linux/arm/v7
- linux/arm/v6
- linux/amd64

This is very weird since the [1.21-alpine tag](https://hub.docker.com/layers/nginx/library/nginx/1.21-alpine/images/sha256-c35699d53f03ff9024ce2c8f6730567f183a15cc27b24453c5d90f0e7542daea?context=explore) has also the following ones:

- linux/ppc64le
- linux/s390x
- linux/386

so something must have gone wring in the push that was made.

**Comment by thresheek** [comment]
The x86 issue is known as there is no `mercurial` anymore in alpine 3.14 for this architecture.  Maybe we should do something about it, but I'd rather wait for alpine to sort it out on their own.

For ppc64le and s390x it seems Docker Library builders are stuck/unavailable, so there isnt much we can do at this moment.

cc @tianon @yosifkit

**Comment by JonasAlfredsson** [comment]
Thanks for the swift response.
Glad that this is a known issue, but I am a little bit unsure what this means. Will Alpine stop serving x86 builds of Nginx and this ARCH should be dropped from my automated builds?

**Comment by yosifkit** [comment]
> make: mkdir: Operation not permitted

`s390x` and `ppc64le` are likely to be suffering the same bug as our `php` image builds https://github.com/docker-library/php/issues/1178#issuecomment-875125309.

**Comment by tianon** [comment]
This is fixed for ppc64le and s390x -- for i386, I'm not convinced it's going to be, but maybe? :shrug: :sweat_smile:

**Comment by JonasAlfredsson** [comment]
That is some good news, thanks for posting the update :)
However, what are the plans for 386 going forward? Should this issue remain open, or will that arch be discontinued for Alpine?

**Comment by thresheek** [comment]
Fixed in `nginx:1.21.4` for Debian and in `nginx:1.21.4-alpine` for Alpine.

**Comment by lucacome** [comment]
It seems like there are still some issues. For example `nginx:1.21.4` is missing `linux/386` even though it's available for `nginx:1.21`.

**Comment by thresheek** [comment]
Hmm, interesting. @yosifkit @tianon ^^^ can you elaborate why that could have happened?

**Comment by yosifkit** [comment]
It is failing to find the `nginx` package on i386.  The `binary-i386` directory seems to be missing on the apt repo for bullseye (but is there for buster): https://nginx.org/packages/mainline/debian/dists/bullseye/nginx/, so it is not getting a `Packages.gz` list. The desired version of `.deb` files do exist in the `pool/nginx/n/` folders.

```console
+ dpkgArch=i386
+ nginxPackages=         nginx=1.21.4-1~bullseye         nginx-module-xslt=1.21.4-1~bullseye         nginx-module-geoip=1.21.4-1~bullseye         nginx-module-image-filter=1.21.4-1~bullseye         nginx-module-perl=1.21.4-1~bullseye         nginx-module-njs=1.21.4+0.7.0-1~bullseye     
+ echo deb https://nginx.org/packages/mainline/debian/ bullseye nginx
+ apt-get update
Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
Get:2 http://security.debian.org/debian-security bullseye-security InRelease [44.1 kB]
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [39.3 kB]
Get:4 http://security.debian.org/debian-security bullseye-security/main i386 Packages [90.4 kB]
Get:5 http://deb.debian.org/debian bullseye/main i386 Packages [8119 kB]
Get:6 http://deb.debian.org/debian bullseye-updates/main i386 Packages [2592 B]
Get:7 https://nginx.org/packages/mainline/debian bullseye InRelease [2860 B]
Fetched 8414 kB in 2s (4958 kB/s)
Reading package lists...
+ apt-get install --no-install-recommends --no-install-suggests -y nginx=1.21.4-1~bullseye nginx-module-xslt=1.21.4-1~bullseye nginx-module-geoip=1.21.4-1~bullseye nginx-module-image-filter=1.21.4-1~bullseye nginx-module-perl=1.21.4-1~bullseye nginx-module-njs=1.21.4+0.7.0-1~bullseye gettext-base curl
Reading package lists...
Building dependency tree...
Reading state information...
E: Version '1.21.4-1~bullseye' for 'nginx' was not found
E: Unable to locate package nginx-module-xslt
E: Unable to locate package nginx-module-geoip
E: Unable to locate package nginx-module-image-filter
E: Unable to locate package nginx-module-perl
E: Unable to locate package nginx-module-njs
```

**Comment by lucacome** [comment]
Ah that makes sense. I saw that the tag for `1.21` was updated and assumed it was `1.21.4`, but it's actually still `1.21.3` for i386 (it was updated for all other archs) https://hub.docker.com/layers/nginx/library/nginx/1.21/images/sha256-387da9849102b73c06e645a8f0f40c72fae755f20d33391596041a4dcf8284a9?context=explore

**Comment by thresheek** [comment]
Ok, should be fixed with todays images for 1.21.1 and 1.20.2.
